In [2]:
import numpy as np

# 1-1

RANDOM 함수를 써서 만든 임의의 숫자 100개를 오름차순으로 정렬하세요.

In [85]:
list1 = np.random.randint(1,101, 100)
list1_sorted = np.sort(list1)
print(list1_sorted)

[  2   4   5   5   8  12  13  13  14  18  19  19  20  21  22  22  23  25
  25  26  28  28  29  29  30  31  32  33  34  34  35  35  35  37  38  39
  40  40  41  41  41  42  43  44  45  46  47  47  50  52  54  55  56  57
  60  61  63  63  64  64  65  65  65  66  66  67  67  69  69  70  71  72
  73  74  75  75  75  77  79  79  80  81  83  83  85  87  88  91  93  93
  94  94  95  96  96  98  98  98  99 100]


# 1-2

임의의 두 4 x 4 matrix A, B를 생성하고, 두 matrix를 곱해 matrix C를 생성하세요. 그 이후에 기존의 공식을 사용하여 matrix C의 inverse matrix를 계산하세요. 그리고, C와 inverse C를 곱해 identity
matrix가 나옴을 확인하세요.

In [198]:
matA = np.random.randint(-5,5, (4,4))
matB = np.random.randint(-5,5, (4,4))
print("Matrix A",matA, "Matrix B",matB, sep='\n')

# 행렬 곱
matC = np.dot(matA, matB)
print('Matrix C',matC,sep='\n')


# 역행렬
matM = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        M_int = np.delete(np.delete(matC,i, axis=0), j, axis=1)
        matM[i,j] = M_int[0,0]*(M_int[1,1]*M_int[2,2] - M_int[1,2]*M_int[2,1]) - M_int[0,1]*(M_int[1,0]*M_int[2,2] - M_int[1,2]*M_int[2,0]) + M_int[0,2]*(M_int[1,0]*M_int[2,1] - M_int[1,1]*M_int[2,0])
            
det = matC[0,0] * matM[0,0] - matC[0,1] * matM[0,1] + matC[0,2] * matM[0,2] - matC[0,3] * matM[0,3]
print('determinant:', det)
C = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        C[i,j] = matM[i,j] * (-1)**(i+j)

matC_inv = 1/det * C.T
print('Inverse Matrix C',matC_inv,sep='\n')


# 단위행렬
I = np.dot(matC, matC_inv)
print('Identity Matrix',I,sep='\n')

Matrix A
[[-3 -3 -1 -4]
 [ 2 -2  0 -5]
 [-5  3 -3  2]
 [ 2 -3  0  2]]
Matrix B
[[ 3  3 -3 -4]
 [-3  0 -4  3]
 [ 4  2 -3  1]
 [-5 -3 -2  1]]
Matrix C
[[ 16   1  32  -2]
 [ 37  21  12 -19]
 [-46 -27   8  28]
 [  5   0   2 -15]]
determinant: -77248.0
Inverse Matrix C
[[ 0.09747825 -0.16865162 -0.12756317 -0.03748964]
 [-0.13727216  0.26087407  0.16078086 -0.01201326]
 [-0.01126243  0.07327051  0.05657104  0.01429163]
 [ 0.03099109 -0.0464478  -0.03497825 -0.07725766]]
Identity Matrix
[[ 1.00000000e+00  2.22044605e-16 -1.66533454e-16  2.77555756e-17]
 [-4.44089210e-16  1.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16  1.00000000e+00]]


In [200]:
# 역행렬
matC= np.array([[1, 2, 3, 5],
              [5, 5, 4, 5],
              [5, 6, 5, 5],
              [5, 5, 5, 5]])

M = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        M_int = np.delete(np.delete(matC,i, axis=0), j, axis=1)
        M[i,j] = M_int[0,0]*(M_int[1,1]*M_int[2,2] - M_int[1,2]*M_int[2,1]) - M_int[0,1]*(M_int[1,0]*M_int[2,2] - M_int[1,2]*M_int[2,0]) + M_int[0,2]*(M_int[1,0]*M_int[2,1] - M_int[1,1]*M_int[2,0])
            
det = matC[0,0] * M[0,0] - matC[0,1] * M[0,1] + matC[0,2] * M[0,2] - matC[0,3] * M[0,3]
print('determinant:', det)
C = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        C[i,j] = M[i,j] * (-1)**(i+j)

matC_inv = 1/det * C.T
print('Inverse Matrix C',matC_inv,sep='\n')


# 단위행렬
I = np.dot(matC, matC_inv)
print('Identity Matrix',I,sep='\n')

determinant: -20.0
Inverse Matrix C
[[-0.25  0.5  -0.75  0.5 ]
 [ 0.   -0.    1.   -1.  ]
 [-0.   -1.   -0.    1.  ]
 [ 0.25  0.5  -0.25 -0.3 ]]
Identity Matrix
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2-1

이분법(bisection method)을 사용하여 주어진 3구간 [‐10,‐1], [‐1,0] 그리고 [0,10] 에서의 𝒇(x)의
해를 구하시오.

In [11]:
def func(x):
    return x**5-9*x**4-x**3+17*x**2-8*x-8
# [-10, -1]
a, b = -10,-1
count1 = 0

while abs(b-a) >= 10**-8:
    count1 += 1
    m = (a + b) / 2
    if func(m) * func(a) <=0:
        b = m
    else:
        a = m

print('[-10, -1]에서의 해:', m, '\n 반복 횟수:', count1)

# [-1, 0]
a, b = -1,0
count2 = 0

while abs(b-a) >= 10**-8:
    count2 += 1
    m = (a + b) / 2
    if func(m) * func(a) <=0:
        b = m
    else:
        a = m

print('[-1, 0]에서의 해:', m, '\n 반복 횟수:', count2)

# [0, 10]
a, b = 0,10
count3 = 0

while abs(b-a) >= 10**-8:
    count3 += 1
    m = (a + b) / 2
    if func(m) * func(a) <=0:
        b = m
    else:
        a = m

print('[0, 10]에서의 해:', m, '\n 반복 횟수:', count3)

count_bi= count1 + count2 + count3

print('총 반복 횟수:', count_bi)

[-10, -1]에서의 해: -1.3875071099027991 
 반복 횟수: 30
[-1, 0]에서의 해: -0.5104293450713158 
 반복 횟수: 27
[0, 10]에서의 해: 8.910696404054761 
 반복 횟수: 30
총 반복 횟수: 87


# 2-2

뉴턴법(Newton’s method)를 사용하여 주어진 3점 𝐱𝟎 =-1,-0.1,10 에서 𝒇(x)의 해를 구하시
오.

In [12]:
def func_diff(x):
    return 5*x**4 - 36*x**3 - 3*x**2 + 34*x - 8

# -10
x0 = -10
x1 = np.Infinity
count1 = 0

while abs(x0-x1) >= 10**-8:
    if count1 == 0 :
        x0 = -10
        x1 = np.Infinity
        
    else:
        x0 = x1
    
    x1 = x0 - func(x0)/func_diff(x0)
    count1 += 1
    
print('x0 = -10에서의 해:', x1, '\n 반복 횟수:', count1)

# 0.1
x0 = -0.1
x1 = np.Infinity
count2 = 0

while abs(x0-x1) >= 10**-8:
    if count2 == 0 :
        x0 = -0.1
        x1 = np.Infinity
        
    else:
        x0 = x1
    
    x1 = x0 - func(x0)/func_diff(x0)
    count2 += 1
    
print('x0 = -0.1에서의 해:', x1, '\n 반복 횟수:', count2)

# 10
x0 = 10
x1 = np.Infinity
count3 = 0

while abs(x0-x1) >= 10**-8:
    if count3 == 0 :
        x0 = 10
        x1 = np.Infinity
        
    else:
        x0 = x1
    
    x1 = x0 - func(x0)/func_diff(x0)
    count3 += 1
    
print('x0 = 10에서의 해:', x1, '\n 반복 횟수:', count3)

count_new = count1 + count2 + count3
print('총 반복 횟수:', count_new)

x0 = -10에서의 해: -1.3875071055826167 
 반복 횟수: 13
x0 = -0.1에서의 해: -0.5104293428178256 
 반복 횟수: 5
x0 = 10에서의 해: 8.910696402960298 
 반복 횟수: 6
총 반복 횟수: 24


# 2-3

In [13]:
def func_diff(x):
    return 5*x**4 - 36*x**3 - 3*x**2 + 34*x - 8

# -10
x0 = 0
x1 = np.Infinity
count1 = 0

while abs(x0-x1) >= 10**-8:
    if count1 == 0 :
        x0 = 0
        x1 = np.Infinity
        
    else:
        x0 = x1

    if count1 == 10:
        break
    
    x1 = x0 - func(x0)/func_diff(x0)
    count1 += 1
    print(x1)
    



-1.0
1.0
0.0
-1.0
1.0
0.0
-1.0
1.0
0.0
-1.0


# 2-4

시컨트법(secant method)를 사용하여 주어진 초기조건에서 𝒇(x)의 해를 구하시오.
(1) x1 = -10, x2 = -9.9 (2) x1 = -0.1, x2 = -0.2 (3) x1 = 10, x2 = 9.9 

In [14]:
# x1 = -10, x2 = -9.9
x1 = -10
x2 = - 9.9
count1 = 0

while abs(x2-x1) >= 10**-8:
    
    x3 = x2 - func(x2)*((x2 - x1) / (func(x2) - func(x1)))
    x1 = x2
    x2 = x3
    count1 += 1

print('x1 = -10, x2 = -9.9에서의 해:', x2, '\n 반복 횟수:', count1)
# x1 = -0.1, x2 = -0.2
x1 = -0.1
x2 = - -0.2
count2 = 0

while abs(x2-x1) >= 10**-8:
    
    x3 = x2 - func(x2)*((x2 - x1) / (func(x2) - func(x1)))
    x1 = x2
    x2 = x3
    count2 += 1

print('x1 = -0.1, x2 = -0.2에서의 해:', x2, '\n 반복 횟수:', count2)
# x1 = 10, x2 = 9.9
x1 = 10
x2 = - 9.9
count3 = 0

while abs(x2-x1) >= 10**-8:
    
    x3 = x2 - func(x2)*((x2 - x1) / (func(x2) - func(x1)))
    x1 = x2
    x2 = x3
    count3 += 1

print('x1 = 10, x2 = 9.9에서의 해:', x2, '\n 반복 횟수:', count3)

count_sec = count1 + count2 + count3
print('총 반복 횟수:', count_sec)

x1 = -10, x2 = -9.9에서의 해: -1.387507105582635 
 반복 횟수: 18
x1 = -0.1, x2 = -0.2에서의 해: -0.5104293428178256 
 반복 횟수: 8
x1 = 10, x2 = 9.9에서의 해: 8.910696402960298 
 반복 횟수: 6
총 반복 횟수: 32


# 2-5

이분법, 뉴턴법, 시컨트법에 대한 계산을 진행하고, 몇 번의 반복계산 후에 해를 구하였는지 서
술하시오.

In [15]:
print('이분법 시행 횟수:', count_bi)
print('뉴턴법 시행 횟수:', count_new)
print('시컨트법 시행 횟수:', count_sec)

이분법 시행 횟수: 87
뉴턴법 시행 횟수: 24
시컨트법 시행 횟수: 32
